config/routes.rb
Rails.application.routes.draw do
  
  root 'admin#index'

  get 'admin/index'
  
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  get 'sessions/new'

  get 'sessions/create'

  get 'sessions/destroy'

  resources :users

  resources :tasks

  resources :archived_tasks

  resources :waits

  #root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/wait.rb
class Wait < ApplicationRecord
	belongs_to :user
	
	def self.search(search)
		#abilito le condizioni di ricerca sul modello
  		where("stato LIKE ? OR chi LIKE ? OR note LIKE ?", "%#{search}%", "%#{search}%", "%#{search}%")
	end
end

app/controllers/waits_controller.rb
class WaitsController < ApplicationController
  def index
		if params[:search]
			@wait = Wait.search(params[:search]).order("data_chiusura") #ricerco e ordino per stato
		else
			#@wait = Wait.all.order("data_chiusura") #ordino i task per "data_chiusura")
      @wait = Wait.where(user_id: session[:user_id])
		end
  end

  def edit
    @wait = Wait.find(params[:id])
  end

  def new
  end

  def create
    #render plain: params[:task].inspect
    @user = User.find_by(id: session[:user_id])
    @wait = Wait.new(params.require(:task).permit(:data_scadenza, :chi, :note))

    @wait.data_apertura = Date.today
    @wait.stato = 'IN SCADENZA'
    @wait.user_id = @user.id
    
    @wait.save
    redirect_to waits_path
  end

  def update
    @wait = Wait.find(params[:id])
    @user = User.find_by(id: session[:user_id])

    if params[:wait][:stato] == 'FATTO' #prendo lo stato e vedo se è uguale a FATTO
      #creo un oggetto archived_task in cui mi salvo i parametri da salvare nella nuova tabella
      @archived_task = ArchivedTask.new(params.require(:wait).permit(:stato, :chi, :note))
      @archived_task.data_apertura = @wait.data_apertura
      @archived_task.data_chiusura = Date.today #salvo la data di chiusura della task da archiviara
      @archived_task.user_id = @user.id

      @archived_task.save

      @wait.destroy #elimino la task che sposto in archivio

      redirect_to archived_tasks_path

    elsif params[:wait][:stato] == 'IN LAVORAZIONE' || params[:wait][:stato] == 'DA FARE' 
      @task = Task.new(params.require(:wait).permit(:stato, :chi, :note))
      @task.data_apertura = @wait.data_apertura
      @task.user_id = @user.id

      @task.save

      @wait.destroy #elimino la task che sposto in altra lista

      redirect_to tasks_path
    elsif params[:wait][:stato] == 'IN SCADENZA'
      @wait.update(params.require(:wait).permit(:data_scadenza, :stato, :chi, :note))
      @wait.user_id = @user.id
      @wait.save

      redirect_to waits_path
    end
  end

  def destroy
    @wait = Wait.find(params[:id])
    @wait.destroy
   
    redirect_to waits_path
  end
end

app/helpers/waits_helper.rb
module WaitsHelper
end

app/views/waits/edit.html.erb
<div class="container-header">
  <div class="container container-header">
    <div class="row">
      <h1>Modifica task a scadenza</h1>
    </div>
  </div>
</div>
<div class="container">
  <div class="panel panel-default">
	  <%= form_for :wait, url: {action: "update"}, method: :patch do |f| %>
	    <table class="table table-bordered table-striped table-striped">    
	      <thead>
	        <div class="row">
	          <tr>
	            <th class="col-xs-3"><%= f.label :data_scadenza %></th>
	            <th class="col-xs-2"><%= f.label :stato %></th>
	            <th class="col-xs-1"><%= f.label :chi %></th>
	            <th class="col-xs-4"><%= f.label :note %></th>
	            <th class="col-xs-2"></th>
	          </tr>
	        </div>
	      </thead>
	      <tbody>     	
	        <div class="row">
	          <tr>
	            <td class="col-xs-3">
	            	<%= f.date_select :data_scadenza,{}, { :class => 'form-control overwrite-formcontrol' } %>
	            </td>
	            <td class="col-xs-2">
	            <%= f.select :stato, [['DA FARE','DA FARE'],['IN LAVORAZIONE','IN LAVORAZIONE'],['IN SCADENZA','IN SCADENZA'],['FATTO', 'FATTO']],{}, { :class => 'form-control' } %>
	            </td>
	            <td class="col-xs-1">
				<%= f.select :chi, [['IO','IO'],['ROMANIA','ROMANIA'],['INDIA','INDIA'],['ORGANIZZAZIONE','ORGANIZZAZIONE']],{}, { :class => 'form-control' } %>
				</td>
	            <td class="col-xs-4">
	            	<%= f.text_area :note, class: "form-control" %>
	            </td>
	            <td class="col-xs-2">
	            	<%= f.submit "Modifica", class: "btn btn-warning" %>
					<%= link_to 'Back', tasks_path, class: "btn btn-default" %>		
	            </td>
	          </tr>
	        </div>        
	      </tbody>   
	    </table>
	  <% end %>
  </div>
</div>

app/views/waits/index.html.erb
<% content_for :menu do %>
  <h1 class="col-xs-6">Task a Scadenza</h1>
<% end %>
<div class="container">
  <div class="pull-right container-actions">
    <%= link_to 'Nuovo Task', new_wait_path, class: "btn btn-default" %>
    <%= link_to 'Tutti i Task', tasks_path, class: "btn btn-success" %>
    <%= link_to 'Task Fatti', archived_tasks_path, class: "btn btn-primary" %>
  </div>
</div>
<div class="container">
  <div class="panel panel-default">
    <table class="table table-bordered table-striped table-striped">
      <thead>
        <div class="row">
          <tr>
            <th class="col-xs-1">Apertura</th>
            <th class="col-xs-2">Scadenza</th>
            <th class="col-xs-1">Stato</th>
            <th class="col-xs-5">Chi</th>
            <th class="col-xs-3"></th>
          </tr>
        </div>
      </thead>
      <tbody>
        <% @wait.each do |t| %>
        <div class="row">
          <tr>
            <td class="col-xs-1"><%= t.data_apertura %></td>
            <td class="col-xs-1"><%= t.data_scadenza %></td>
            <td class="col-xs-2"><%= t.stato %></td>
            <td class="col-xs-1"><%= t.chi %></td>
            <td class="col-xs-5"><%= t.note %></td>
            <td class="col-xs-3">
              <%= link_to 'Modifica', edit_wait_path(t), class: "btn btn-warning btn-sm" %>
            </td>
          </tr>
        </div>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/waits/new.html.erb
<% content_for :menu do %>
  <h1 class="col-xs-6">Crea un nuovo task a scadenza</h1>
<% end %>
<div class="container">
  <div class="panel panel-default">
	  <%= form_for :task, url: {action: "create"} do |f| %>
	    <table class="table table-bordered table-striped table-striped">    
	      <thead>
	        <div class="row">
	          <tr>
	            <th class="col-xs-2"><%= f.label :data_scadenza %></th>
	            <th class="col-xs-2"><%= f.label :chi %></th>
	            <th class="col-xs-5"><%= f.label :note %></th>
	            <th class="col-xs-3"></th>
	          </tr>
	        </div>
	      </thead>
	      <tbody>     	
	        <div class="row">
	          <tr>
	            <td class="col-xs-2">
	            	<%= f.date_select :data_scadenza,{}, { :class => 'form-control overwrite-formcontrol' } %>
	            </td>
	            <td class="col-xs-2">
					<%= f.select :chi, [['IO','IO'],['ROMANIA','ROMANIA'],['INDIA','INDIA'],['ORGANIZZAZIONE','ORGANIZZAZIONE']],{}, { :class => 'form-control' } %>
	            </td>
	            <td class="col-xs-5"><%= f.text_area :note, class: "form-control" %></td>
	            <td class="col-xs-3">
	            	<%= f.submit "Aggiungi", class: "btn btn-success" %>	
	            	<%= link_to 'Back', tasks_path, class: "btn btn-default" %>			
	            </td>
	          </tr>
	        </div>        
	      </tbody>   
	    </table>
	  <% end %>
  </div>
</div>