config/routes.rb
Rails.application.routes.draw do
  
  root 'admin#index'

  get 'admin/index'
  
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  get 'sessions/new'

  get 'sessions/create'

  get 'sessions/destroy'

  resources :users

  resources :tasks

  resources :archived_tasks

  resources :waits

  #root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/task.rb
class Task < ApplicationRecord
	belongs_to :user

	def self.search(search)
		#abilito le condizioni di ricerca sul modello
  		where("stato LIKE ? OR chi LIKE ? OR note LIKE ?", "%#{search}%", "%#{search}%", "%#{search}%")
	end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

	def index
		if params[:search]
			@task = Task.search(params[:search]).order("stato")
		else
			#@task = Task.all.order("stato") #ordino i task
			@task = Task.where(user_id: session[:user_id]).order("stato")
		end
	end

	def show
		@task = Task.find(params[:id])
	end

	def new
	end

	def edit
		@task = Task.find(params[:id])
	end

	def create
		#render plain: params[:task].inspect
		@user = User.find_by(id: session[:user_id])
		@task = Task.new(params.require(:task).permit(:stato, :chi, :note))

		@task.data_apertura = Date.today
		@task.user_id = @user.id

		@task.save
		redirect_to tasks_path
	end

	def update
		@task = Task.find(params[:id])
		
		# !!!!!!!prendere un solo parametro
		if params[:task][:stato] == 'FATTO' #prendo lo stato e vedo se è uguale a FATTO
			
			#creo un oggetto archived_task in cui mi salvo i parametri da salvare nella nuova tabella
			@user = User.find_by(id: session[:user_id])
			@archived_task = ArchivedTask.new(params.require(:task).permit(:data_apertura, :stato, :chi, :note))
			
			@archived_task.data_chiusura = Date.today #salvo la data di chiusura della task da archiviara
			@archived_task.user_id = @user.id

			@archived_task.save

			@task.destroy #elimino la task che sposto in archivio

			redirect_to archived_tasks_path

		elsif @task.update(params.require(:task).permit(:data_apertura, :stato, :chi, :note))
			redirect_to tasks_path
		else
			render 'edit'
		end
	end

	def destroy
	  @task = Task.find(params[:id])
	  @task.destroy
	 
	  redirect_to tasks_path
	end

end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/edit.html.erb
<% content_for :menu do %>
  <h1 class="col-xs-6">Modifica il task</h1>
<% end %>
<div class="container">
  <div class="panel panel-default">
	  <%= form_for :task, url: {action: "update"}, method: :patch do |f| %>
	    <table class="table table-bordered table-striped table-striped">    
	      <thead>
	        <div class="row">
	          <tr>
	            <th class="col-xs-3"><%= f.label :data_apertura %></th>
	            <th class="col-xs-2"><%= f.label :stato %></th>
	            <th class="col-xs-1"><%= f.label :chi %></th>
	            <th class="col-xs-4"><%= f.label :note %></th>
	            <th class="col-xs-2"></th>
	          </tr>
	        </div>
	      </thead>
	      <tbody>     	
	        <div class="row">
	          <tr>
	            <td class="col-xs-3">
	            	<%= f.date_select :data_apertura,{}, { :class => 'form-control overwrite-formcontrol' } %>
	            </td>
	            <td class="col-xs-2">
					<%= f.select :stato, [['DA FARE','DA FARE'],['IN LAVORAZIONE','IN LAVORAZIONE'],['FATTO','FATTO']],{}, { :class => 'form-control' } %>
	            </td>
	            <td class="col-xs-1"><%= f.select :chi, [['IO','IO'],['ROMANIA','ROMANIA'],['INDIA','INDIA'],['ORGANIZZAZIONE','ORGANIZZAZIONE']],{}, { :class => 'form-control' } %></td>
	            <td class="col-xs-4">
	            	<%= f.text_area :note, class: "form-control" %>
	            </td>
	            <td class="col-xs-2">
	            	<%= f.submit "Modifica", class: "btn btn-warning" %>
					<%= link_to 'Back', tasks_path, class: "btn btn-default" %>		
	            </td>
	          </tr>
	        </div>        
	      </tbody>   
	    </table>
	  <% end %>
  </div>
</div>

app/views/tasks/index.html.erb
<% content_for :menu do %>
  <h1 class="col-xs-6">ALL task</h1>
<% end %>
<div class="container">
  <div class="pull-right container-actions">
    <%= link_to 'Nuovo Task', new_task_path, class: "btn btn-default" %>
    <%= link_to 'Task Fatti', archived_tasks_path, class: "btn btn-success" %>
    <%= link_to 'In scadenza', waits_path, class: "btn btn-warning" %>
  </div>
</div>
<div class="container">
  <div class="panel panel-default">
    <table class="table table-bordered table-striped table-striped">
      <thead>
        <div class="row">
          <tr>
            <th class="col-xs-1">Apertura</th>
            <th class="col-xs-2">Stato</th>
            <th class="col-xs-1">Chi</th>
            <th class="col-xs-5">Note</th>
            <th class="col-xs-3"></th>
          </tr>
        </div>
      </thead>
      <tbody>
        <% @task.each do |t| %>
        <div class="row">
          <tr>
            <td class="col-xs-1"><%= t.data_apertura %></td>
            <td class="col-xs-2"><%= t.stato %></td>
            <td class="col-xs-1"><%= t.chi %></td>
            <td class="col-xs-5"><%= t.note %></td>
            <td class="col-xs-3">
              <%= link_to 'Mostra', task_path(t), class: "btn btn-success btn-sm" %>
              <%= link_to 'Modifica', edit_task_path(t), class: "btn btn-warning btn-sm" %>
              <%= link_to 'Elimina', task_path(t), method: :delete, data:{ confirm: 'Sicuro di voler eliminare la Task??', class: "alert alert-warning" }, class: "btn btn-danger btn-sm" %>
            </td>
          </tr>
        </div>
        <% end %>
      </tbody>
      
    </table>
    
  </div>
</div>

app/views/tasks/new.html.erb
<% content_for :menu do %>
  <h1 class="col-xs-6">Crea un nuovo task</h1>
<% end %>
<div class="container">
  <div class="panel panel-default">
	  <%= form_for :task, url: {action: "create"} do |f| %>
	    <table class="table table-bordered table-striped table-striped">    
	      <thead>
	        <div class="row">
	          <tr>
	            <th class="col-xs-2"><%= f.label :stato %></th>
	            <th class="col-xs-2"><%= f.label :chi %></th>
	            <th class="col-xs-5"><%= f.label :note %></th>
	            <th class="col-xs-3"></th>
	          </tr>
	        </div>
	      </thead>
	      <tbody>     	
	        <div class="row">
	          <tr>
	            <td class="col-xs-2">
	            	<%= f.select :stato, [['DA FARE','DA FARE'],['IN LAVORAZIONE','IN LAVORAZIONE'],['FATTO','FATTO']],{}, { :class => 'form-control' }%>
	            </td>
	            <td class="col-xs-2">
					<%= f.select :chi, [['IO','IO'],['ROMANIA','ROMANIA'],['INDIA','INDIA'],['ORGANIZZAZIONE','ORGANIZZAZIONE']],{}, { :class => 'form-control' } %>
	            </td>
	            <td class="col-xs-5"><%= f.text_area :note, class: "form-control" %></td>
	            <td class="col-xs-3">
	            	<%= f.submit "Aggiungi", class: "btn btn-success" %>	
	            	<%= link_to 'Back', tasks_path, class: "btn btn-default" %>			
	            </td>
	          </tr>
	        </div>        
	      </tbody>   
	    </table>
	  <% end %>
  </div>
</div>

app/views/tasks/show.html.erb
<% content_for :menu do %>
  <h1 class="col-xs-6">Ecco il tuo task</h1>
<% end %>
<div class="container">
  <div class="pull-right container-actions">
    <%= link_to 'Back', tasks_path, class: "btn btn-default" %>
	<%= link_to 'Modifica', edit_task_path(@task), class: "btn btn-warning" %>
  </div>
</div>
<div class="container">
  <div class="panel panel-default">
    <table class="table table-bordered table-striped table-striped">
      <thead>
        <div class="row">
          <tr>
            <th class="col-xs-2">Data inserimento</th>
            <th class="col-xs-2">Stato</th>
            <th class="col-xs-5">Note</th>
            <th class="col-xs-3"></th>
          </tr>
        </div>
      </thead>
      <tbody>
        <div class="row">
          <tr>
            <td class="col-xs-2"><%= @task.data_apertura %></td>
            <td class="col-xs-2"><%= @task.stato %></td>
            <td class="col-xs-5"><%= @task.note %></td>
            <td class="col-xs-3"></td>
          </tr>
        </div>
      </tbody>
    </table>
  </div>
</div>
 