config/routes.rb
Rails.application.routes.draw do
  
  root 'admin#index'

  get 'admin/index'
  
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  get 'sessions/new'

  get 'sessions/create'

  get 'sessions/destroy'

  resources :users

  resources :tasks

  resources :archived_tasks

  resources :waits

  #root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/archived_task.rb
class ArchivedTask < ApplicationRecord
	belongs_to :user
	
	def self.search(search)
		#abilito le condizioni di ricerca sul modello
		where("chi LIKE ? OR note LIKE ?", "%#{search}%", "%#{search}%")
	end
end

app/controllers/archived_tasks_controller.rb
class ArchivedTasksController < ApplicationController
  	def index
		if params[:search]
			@archived_task = ArchivedTask.search(params[:search]).order("data_chiusura") #ricerco e ordino per stato
		else
			#@archived_task = ArchivedTask.all.order("data_chiusura") #ordino i task per "data_chiusura")
			@archived_task = ArchivedTask.where(user_id: session[:user_id])
		end
  	end

  	def edit
  		@archived_task = ArchivedTask.find(params[:id])
  	end

  	def update
		@archived_task = ArchivedTask.find(params[:id])
		
		if params[:archived_task][:stato] != 'FATTO'

			@task = Task.new(params.require(:archived_task).permit(:data_apertura, :stato, :chi, :note))
			@task.save

			@archived_task.destroy #elimino la task dall'archivio

			redirect_to tasks_path

		else
			render 'edit'
		end
   	end

	def destroy
	  	@archived_task = ArchivedTask.find(params[:id])
	 	@archived_task.destroy
	 
	  	redirect_to tasks_path
	end

end

app/helpers/archived_tasks_helper.rb
module ArchivedTasksHelper
end

app/views/archived_tasks/edit.html.erb
<h1>Modifica task archiviato</h1>

<%= form_for :archived_task, url: {action: "update"}, method: :patch do |f| %>

	<%= f.label :data_apertura %><br>
	<%= f.date_select :data_apertura %><br>

	<%= f.label :stato %><br>
	<%= f.select :stato, [['DA FARE','DA FARE'],['IN LAVORAZIONE','IN LAVORAZIONE']] %><br>
	
	<%= f.label :chi %><br>
	<%= f.select :chi, [['IO','IO'],['ROMANIA','ROMANIA'],['INDIA','INDIA'],['ORGANIZZAZIONE','ORGANIZZAZIONE']] %><br>

	<%= f.label :note %><br>
	<%= f.text_area :note %><br>

	<%= f.submit "Modifica", class: "aggiungi" %>
	<%= link_to 'Back', archived_tasks_path %>

<% end %>

app/views/archived_tasks/index.html.erb
<div class="container-header">
  <div class="container container-header">
    <div class="row">
      <h1 class="col-xs-6">Task Fatti e Archiviati</h1>
      <div class="col-xs-6 container-search">
        <%= form_tag(tasks_path, :method => "get", id: "search-form") do %>
          <%= text_field_tag :search, params[:search], placeholder: "Ricerca per Note, Chi o Stato", class: "search" %>
          <%= submit_tag "Cerca", class: "btn btn-default btn-sm" %>
        <% end %>
      </div>
    </div>
  </div>
</div>
<div class="container">
  <div class="pull-right container-actions">
    <%= link_to 'Tutti i Task', tasks_path, class: "btn btn-success" %>
    <%= link_to 'In scadenza', waits_path, class: "btn btn-warning" %>
  </div>
</div>
<div class="container">
  <div class="panel panel-default">
    <table class="table table-bordered table-striped table-striped">
      <thead>
        <div class="row">
          <tr>
            <th class="col-xs-1">Apertura</th>
            <th class="col-xs-2">Stato</th>
            <th class="col-xs-1">Chi</th>
            <th class="col-xs-5">Note</th>
            <th class="col-xs-3"></th>
          </tr>
        </div>
      </thead>
      <% @archived_task.each do |t| %>
      <tbody>
        <div class="row">
          <tr>
            <td class="col-xs-1"><%= t.data_apertura %></td>
            <td class="col-xs-1"><%= t.data_chiusura %></td>
            <td class="col-xs-2"><%= t.stato %></td>
            <td class="col-xs-1"><%= t.chi %></td>
            <td class="col-xs-5"><%= t.note %></td>
            <td class="col-xs-3">
              <%= link_to 'Modifica', edit_archived_task_path(t), class: "btn btn-warning btn-sm" %>
            </td>
          </tr>
        </div>
      </tbody>
      <% end %>
    </table>
  </div>
</div>